### ISSUE TITLE
No notifications when sideloaded with TrollStore

### ISSUE THREAD

**Issue by makief01** [level3tjg/TwitchAdBlock#1]
Not receiving any notifications from the app.
The app is sideloaded with TrollStore (as opposed to AltStore where this is the expected behavior).
Notifications are enabled both in the app and in iOS Settings.

App Version: 13.9_0.0.8
iOS Version: 15.1.1
TrollStore Version: 1.2

**Comment by level3tjg** [comment]
Looks like theos-jailed removed entitlements... I updated the ipa for [v13.9_0.0.8](https://github.com/level3tjg/TwitchAdBlock/releases/tag/v13.9_0.0.8) release, could you try the new one and test if notifications work?

**Comment by makief01** [comment]
That fixed it!
I am receiving notifications now.
Thanks!
