### ISSUE TITLE
Video no playing

### ISSUE THREAD

**Issue by rctfan929** [level3tjg/TwitchAdBlock#10]
Video does not play when ad block proxy and custom proxy are turned on.
![17FEB81D-B5C4-4528-A025-45DA1D34A98B](https://github.com/level3tjg/TwitchAdBlock/assets/46878212/0b20e227-9d2a-40ec-99df-2d49e04e03c0)

![47BA858D-21C9-4CD7-94DD-A201589627A0](https://github.com/level3tjg/TwitchAdBlock/assets/46878212/1b9113cd-48da-4854-8585-a5f506faab2a)

**Comment by SparkRenegade** [comment]
How do you get this to even work? I downloaded all three of them. There in my files on my phone. What do I do?

**Comment by rctfan929** [comment]
> How do you get this to even work? I downloaded all three of them. There in my files on my phone. What do I do?

**Comment by level3tjg** [comment]
I've taken my proxy server down as I've stopped maintaining it, I'd suggest using `https://eu.luminous.dev/live/:channel` instead

**Comment by rctfan929** [comment]
I put that in the custom proxy and videos still don’t play.

**Comment by dfurth** [comment]
I have the same issue. Using the provided custom proxy does not work properly. Please open this issue again
