### ISSUE TITLE
Recommended proxy not working (An error occurred)

### ISSUE THREAD

**Issue by dfurth** [level3tjg/TwitchAdBlock#11]
I'm currently having the same issue as #10

The provided proxy of `https://eu.luminous.dev/live/:channel` does not work, the same error appears. 

![image](https://github.com/level3tjg/TwitchAdBlock/assets/118046170/1e91eca6-0d39-42cb-832e-af0d2a14a207)

**Comment by JackPlaysGames0510** [comment]
I don’t think it has anything to do with servers I think it’s the tweak itself but if you downgrade 16.4 you will be fine and it will get rid of though stupid story as well

**Comment by level3tjg** [comment]
I've re-implemented the proxy functionality to use standard HTTPS proxy servers. If for some reason you still need to use a proxy I would recommend using the default and leaving custom proxy off.
