### ISSUE TITLE
after twitch update an error occurred  pops up  (16.5)

### ISSUE THREAD

**Issue by lqr1** [level3tjg/TwitchAdBlock#12]
![image](https://github.com/level3tjg/TwitchAdBlock/assets/128184565/e2f05158-a517-4cdf-a5a2-23499a107f40)

i have to disable the Adblock so i can watch any stream

**Comment by JackPlaysGames0510** [comment]
Just downgrade to 16.4 nothing is different

**Comment by level3tjg** [comment]
Fixed in 31292e5bd84d1622dc147e3aa681f1d37f33a045

**Comment by JackPlaysGames0510** [comment]
thanks man
