### ISSUE TITLE
Ads Play When Going From Clip To Full Video

### ISSUE THREAD

**Issue by StephenWolters** [level3tjg/TwitchAdBlock#18]
Watch a Clip > Click "Watch Full Video" > Ad(s) Play Before Video Starts

**Comment by level3tjg** [comment]
Could you try the latest build and let me know if this is still an issue? Latest build artifact can be found [here](https://github.com/level3tjg/TwitchAdBlock/actions/runs/8495980232#artifacts)

**Comment by StephenWolters** [comment]
Seems fixed, thanks!
