### ISSUE TITLE
Instant Crash on Load up - TwitchAdBlock v18.8.2-0.1.1

### ISSUE THREAD

**Issue by ThatGuy0rion** [level3tjg/TwitchAdBlock#19]
The new IPA (v18.8.2-0.1.1) when sideloaded via Altstore instantly crashing upon loading.

Edit: Sideloading via Sideloadly works with no issue, you can open the app and use it as normal.

**Comment by chedger** [comment]
I'm having the same issue after installing from Altstore. I'd prefer not to use Sideloady, so hopefully this is fixed.

**Comment by asdfzxcvbn** [comment]
can you attach a crash log?

**Comment by chedger** [comment]
Where do I get a crash log?

**Comment by asdfzxcvbn** [comment]
> Where do I get a crash log?

settings -> privacy and security -> analytics & improvements -> analytics data, then search for "twitch" and upload the text to pastebin or something

**Comment by chedger** [comment]
https://pastebin.com/VE8G9krK

**Comment by chedger** [comment]
> > Where do I get a crash log?
> 
> 
> 
> settings -> privacy and security -> analytics & improvements -> analytics data, then search for "twitch" and upload the text to pastebin or something

https://pastebin.com/VE8G9krK

**Comment by level3tjg** [comment]
This was caused by changes to the sideloaded patches, I've updated the latest release with new builds that work on AltStore

**Comment by chedger** [comment]
Why was this closed?
