### ISSUE TITLE
What's the reason for moving to HTTP(S) proxies over m3u8?

### ISSUE THREAD

**Issue by zGato** [level3tjg/TwitchAdBlock#22]
Hello, would like to ask what's the main reason for this change? Both solutions do the same, but m3u8 proxies having the ability to modify traffic (such as modifying client name, user agent, ...)
The proxy that's being used by default (TTV LOL PRO public proxy) is not meant to be used for this, but my public and free m3u8 proxies are.

At TTV LOL PRO we're suffering from Twitch rate limiting us because of how is built, and this doesn't help, whilst normal m3u8 proxies don't have any of these issues.

I support your good intentions on making this app, however, not wanting to support your own proxy (but having donation pages) and thus gaining benefit from third party ones is not nice. Least is asking.

Thank you,

**Comment by level3tjg** [comment]
I switched from m3u8 proxies for ease of use, free http proxy servers are more common. The amount of users using proxies shouldn't be very high anyways, the method I'm using to block server ads still works and proxying was only meant as a backup if that ever fails (it's also disabled by default). If you'd like I can add any donation links you have to the tweak and depiction or simply remove your proxy as the default, or whatever you want really. Apologies for all of the extra traffic, I wouldn't expect there'd be many proxy users but maybe I'm wrong.

**Comment by zGato** [comment]
Free http proxies are more common true, however, there's a bunch of m3u8 public proxies aswell that have been running for years, so I doubt those are going away anytime soon (atleast mines are not going away for a looong time)

I have not monitored the amount of users coming from your specific app, as I have well over 1M logged requests per day, just a quick screenshot so you see:
![image](https://github.com/level3tjg/TwitchAdBlock/assets/88756568/036aff02-e237-470b-bf57-6c3f692b3cfb)
So it's hard for me to monitor that, however I've been blocking a few user agents for a while so not sure if your app is able to hit the proxy in the first place (don't have an iOS device I can test unfortunately)

It's all good, don't worry, keep the proxy there, I don't mind really, but IMHO m3u8 proxies are way better than using standard http proxies, but at the same time I'm not the dev of this, so it's up to you.

Thank you,
