### ISSUE TITLE
[Discussion] Enable Turbo?

### ISSUE THREAD

**Issue by makief01** [level3tjg/TwitchAdBlock#32]
Instead of *literally* blocking ads, is it possible to force Turbo to be enabled on the client to achieve the same result?

**Comment by zGato** [comment]
Turbo is server-sided, same as Twitch ads, your client can't control that.

**Comment by Tgod1991** [comment]
> Turbo is server-sided, same as Twitch ads, your client can't control that.

I been using modified Twitch app and seems to be blocking ads. ![image](https://github.com/user-attachments/assets/13344d16-4e2e-4abc-8017-e12300e0e76a)

**Comment by zGato** [comment]
> > Turbo is server-sided, same as Twitch ads, your client can't control that.
> 
> I been using modified Twitch app and seems to be blocking ads.

Cause their shit is all messed up. You used to be able to just not get any ads if you rejected cookies in the EU, for months lmao.

**Comment by level3tjg** [comment]
Twitch doesn't check client-side if you have turbo before showing ads, whether ads are shown or not is determined by the server when you fetch the stream. Their shit is definitely all messed up though, if you have the tweak enabled the server responds saying you should get stitched ads but for some reason never sends them. Still don't know why that is, it doesn't work on any other platform.
